# Generated by Django 3.2.7 on 2021-09-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('recurrence', models.IntegerField()),
                ('day', models.DateField()),
                ('UserId', models.IntegerField()),
            ],
        ),
    ]
