# Generated by Django 3.2.7 on 2021-09-10 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='UserId',
            new_name='user_id',
        ),
    ]
