# Generated by Django 3.2.7 on 2021-09-14 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_alter_reminder_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='user_id',
            new_name='user',
        ),
    ]
