# Generated by Django 3.2.7 on 2021-09-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_rename_user_id_reminder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
